---
- name: TESTE
  hosts: fortigates
  gather_facts: no

  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
    fw_services:
      - ping
      - https
      - ssh
      - http
      - fgfm

  tasks:
    - name: Configure interface Port2
      # system_global:
      #       hostname: "{{ firewall_name }}"
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        system_interface:
          interface: port3
          mode: dhcp
          allowaccess: "{{ __service }}"
          type: physical
          alias: "REDHAT"
          snmp_index: "3"

      loop: "{{ fw_services }}"
      loop_control:
        loop_var: __service
