---
- hosts: fortigates
  gather_facts: no

  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Configura Firewall Address
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_address:
          name: "VPN_local_subnet_1"
          uuid: 156918c8-02e6-51ed-b788-8662b01661ca
          allow_routing: "enable"
          subnet: 172.16.190.0 255.255.255.0
