---
- name: TESTE
  hosts: fortigates
  gather_facts: no

  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Configure interface
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        system_interface:
          name: port3
          mode: static
          ip: 172.16.190.27/24
          status: up
          allowaccess: [ping, https, ssh, http]
          type: physical
          alias: "REDHAT"
          snmp_index: "3"
