---
- name: TESTE
  hosts: fortigates
  gather_facts: no

  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Configure interface
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "absent"
        system_interface:
          name: port2
          mode: dhcp
          status: up
          allowaccess: []
          type: physical
          alias: ""
          snmp_index: "2"
