---
- hosts: fortigates
  gather_facts: no

  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - fortios_vpn_ipsec_phase2_interface:
        state: "present"
        vdom: "{{ vdom }}"
        vpn_ipsec_phase2_interface:
          name: "VPN-REDHAT-2"
          phase1name: "VPN-REDHAT"
          proposal: ["des-md5", "des-sha1"]
          comments: "VPN created by Ansible"
          src_addr_type: name
          dst_addr_type: name
          src_name: "VPN_REDHAT_local"
          dst_name: "VPN_REDHAT_remote"
