---
- name: TESTE - gathering fortimanager facts
  hosts: fortigates
  gather_facts: no
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:

  - name: Activate FortiToken
    fortios_monitor:
       vdom: "root"
       selector: 'save.system.config'


  - name: Reboot This Device
    fortios_monitor:
       vdom: "root"
       selector: 'reboot.system.os'
       params:
           event_log_message: 'Reboot Request From Ansible'
