---
- name: TESTE
  hosts: fortigates
  gather_facts: no
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   host: "172.16.0.128"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure virtual IP for IPv4.
    fortios_firewall_vip:
      host:  "{{ host }}"
      username: "admin"
      password: "Fortinet1!"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify:  "{{ ssl_verify }}"
      state: "present"
      firewall_vip:
        name: "testfwvip"
        extip: "1.1.1.1-1.1.1.4"
        extintf: "any"
        mappedip:
         -
            range: "1.1.2.1-1.1.2.4"

