---
- name: CONFIGURE FIREWALL POLICY
  hosts: fortigates
  connection: local
  gather_facts: False
  tasks:
    - name: CREATE ADOM REVISION
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "dmz"
        created_by: "automation"
        description: "Weekly ADOM Revision"
        revision_name: "Revision_MM/DD/YY"

    - name: RESTORE REVISION
      fortimgr_revision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        adom: "dmz"
        created_by: "user"
        description: "ADOM Revert"
        revision_name: "Last Good Revision"
        restore_name" "Rollback"
        state: "restore"
