---
- name: TESTE
  hosts: fortigates
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
    fw_services:
      - ping
      - https
      - ssh
      - http

  tasks:
    - name: Configure interface Port1
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        system_interface:
          ac_name: "port1"
          mode: dhcp
          allowaccess: "{{ __service }}"
          type: physical
          alias: "Gerencia"
          snmp_index: "1"
      loop: "{{ fw_services }}"
      loop_control:
        loop_var: __service
